class TestData:
    CHROME_PATH = "C:/Program Files (x86)/chromedriver.exe"
    recalls01url = "https://www.consumeraffairs.com/recalls/liberty-mountain-recalls-birdie-belay-devices-032921.html#"
    disclaimerexpectedtext = "ConsumerAffairs is not a government agency and may be compensated by companies displayed. How it works."
    footerexpectedcopyright = "Copyright © 2021 Consumers Unified LLC. All Rights Reserved. The contents of this site may not be republished, reprinted, rewritten or recirculated without written permission."
    footerexpectedbody = "ConsumerAffairs is not a government agency. Companies displayed may pay us to be Authorized or when you click a link, call a number or fill a form on our site. Our content is intended to be used for general information purposes only. It is very important to do your own analysis before making any investment based on your own personal circumstances and consult with your own investment, financial, tax and legal advisers."
    socialmailto = "test@consumeraffairs.com"
    twitterurl = "https://twitter.com/"
    contactusurl = "https://www.consumeraffairs.com/about/contact/"
    faqurl = "https://www.consumeraffairs.com/about/faq/"
    terms_of_useurl = "https://www.consumeraffairs.com/about/terms_of_use/"
    privacypolicyurl = "https://www.consumeraffairs.com/about/privacy_policy/"
    canoticeurl = "https://www.consumeraffairs.com/about/privacy_policy/#california-consumers"